### ISSUE TITLE
enum type for which ppx generate a types

### ISSUE THREAD

**Issue by mattdamon108** [zth/rescript-relay#277]
Hi,

I got generated types for the enum type of the graphQL schema.

```rescript
type enum_Weight = [> #KG | #G | #MG] // from Query

type weightInput = [#KG | #G | #MG] // for the input of Mutation
```

It totally makes sense to me that the `enum_Weight` type from the query, the polymorphic variant has the lower bound and `weightInput` type for the input argument of mutation has no bounds. But there's a little inconvenience with type conflict between them such as the below use case.

```rescript
let product = Query.use()

let (weight, setWeight) = React.Uncurried.useState(_ => product.weight)

let input = Mutation.make_input(~weight=weight) // Error occur

/*
This has type:
    Query_product_graphql.Types.enum_Weight
  Somewhere wanted: [#G | #KG | #MG]
*/
```

Using a simple convert function solves this conflict very easily, but I just wonder if there's a better way or hidden util function or makeInput function for this case.

**Comment by zth** [comment]
So this is a pretty interesting issue, that doesn't have a clear solution that's without trade offs. In short there's _currently_ no better way of doing what you're doing (and yes, it's annoying to have to write that yourself). Why it functions the way it does as of now is because you must map the enum yourself in order to be completely sure you're sending what you think you're sending, since the enum might've changed on the server after you deployed your code.

Anyway, I know that take is very rigid, and there are of course scenarios where that amount of "safety" is unnecessary, or where you're willing to sacrifice safety for ergonomics. For the variables case it's less dangerous since the server will catch any invalid enum you send its way, but if you use this in other parts of your code, you might end up in a scenario where you're passing around something that isn't what you think it is, which might produce weird, hard to find bugs further down in your app.

I've thought about a few potential improvements here:
1. Provide an `unsafeConvert` function that just casts between those two enum types. I don't particularly like this, but it might be the best trade off for some. I just worry that if I add that, developers might be tempted to start using that when they really shouldn't.
2. Generate a converter function that maps between the values for real. This could be opt-in per enum with something like a directive (`weight @rescriptRelayEnumMapper` or similar). The biggest issue for this though is that placing that in the generated Relay files means it'd be duplicated for every place you want the mapper, even if it's for the same enum. And that gives unnecessary bundle bloat in a larger application.
3. Expanding on number 2, instead of placing it in the generated operation file, output a new file for each enum, and include the autoconverter in there. This requires some potentially deep changes to the compiler though, that I'd rather not make
4. Provide codegen via the `rescript-relay-cli` that generates `enumFromString` functions for the enums you configure it to.

Do you have any immediate thoughts here?

**Comment by mattdamon108** [comment]
Thank you for your explanation and consideration. I'd like to change our point of view a little bit. What if we change the type for enum type of Query without the lower bound which is same to the type for the mutation input.

```
# current
type enum_Weight = [> #KG | #G | #MG] // from Query

# changed
type enum_Weight = [#KG | #G | #MG]
```

What would the trade-offs be? I think it could be more sound in type level in the sense that we specify the same type(without lower bound) for the same enum type of graphQL schema. Currently, I think the ppx generates two different polymorphic variants for the same enum type.

>  Why it functions the way it does as of now is because you must map the enum yourself in order to be completely sure you're sending what you think you're sending, since the enum might've changed on the server after you deployed your code.

This is also very good point. Regardless of the server side validation, I think it is more sound type specification for the same enum type.

I'm looking forward to your thought.

**Comment by zth** [comment]
The trade off for not having the lower bound is that that won't force you to deal with the fact that the enum might change after you've deployed your code. Having the lower bound (and `private`) means you're forced to always account for unmatched cases, which will ensure you write your code in a way that is resilient to changes on the server. I've detailed it a bit more [here](https://rescript-relay-documentation.vercel.app/docs/enums).

Let's do a tiny example. Imagine you have a `User` type with the field `role`. That `role` field is of the enum type `UserRole`, which looks like this when you deploy your frontend app:
```
enum UserRole {
  Admin
  Observer
}
```

You get that from the server response, and you maybe pass that along to some mutation. All is well and good.

Then, your server adds a member to the enum, `HiddenAdmin`. Now, any user you get back from the server might have that value in the `role` field, but your code still thinks it can only be either of `Admin` or `Observer`. Any pattern matches on `role` will break with a weird runtime error, and you'd pass that value around thinking it's something it might not be, potentially leading to weird bugs.

The lower bound _forces_ you to handle the fact that the server might've changed the enum before you've had a chance to fix that in your code. The tradeoff here is that you can't _construct_ a type of that, because we're leveraging the type system in a way that lets us force you to handle the default case.

Does this make sense? Would an `enum_Weight_unsafeToInput` help? `let input = Mutation.make_input(~weight=weight->enum_Weight_unsafeToInput)`. It would just cast from one to the other, which might be a bad idea in a lot of cases, but the server will still catch invalid values.

**Comment by mattdamon108** [comment]
I got your point more precisely now. Thank you for your kind explanation. I think it is quite an interesting and important issue to discuss. Let me summarize our issue.

* The polymorphic variant with lower bound will enforce users to handle the unmatched response for enum type. It will prevent the weird bug in the client application caused by server response changed after the client application has already deployed.

In my opinion, it is another concern. The change of server response or schema should be resolved in another way. In your opinion, our client applications should be all wrapped by `option` or `result` type.

If the server response changes happened, I think our client application should be broken in the manner of the type safety so that we can fix it properly and timely. That is the one of best benefits we can get from the sound type system as rescript has. I think that the client application like a walking zombie could be more problem and disaster.

Furthermore, I think GraphQL has the null field type for that. If the response value is expected to be changed later or the client application needs to be working properly at some level even though the API version changed, they should write the field in null field type in schema or they shouldn't use the enum type for that field.

If schema says this field is an enum type and non-null field. I think it should be the polymorphic variant without a lower bound. It will be much helpful and beneficial with the sound type system in run time.

And also, one polymorphic variant for one enum type goes for the type safety. Once the data is parsed properly, then our application guarantees to work and not to have a run time error with the sound type system.

**Comment by mattdamon108** [comment]
Actually, this issue is also discussed in my team. I found additional interesting points to share with you.

* `FutureAddedValue` in [graphql-ppx](https://graphql-ppx.com/docs/future-added-values/), it is aligned to your opinion. I think the graphql-ppx has two options such as an additional option to turn on/off, directive `@ppxOmitFutureValue`.
* Unfortunately, I can not find the related specification or requirement from the GraphQL spec or Relay spec. Can I ask what specification you were based on for adding the lower bound?

**Comment by zth** [comment]
I don't seem to be making my point clear enough 🙂 This isn't about nullability, and it's not something I've made up myself. It's about the fact that in GraphQL, while not governed by the spec, changes to enums and unions aren't considered breaking schema changes. So, this is the ReScript take on what Relay does automatically with `%future added value`. There's some more context you can [read up on here](https://github.com/facebook/relay/issues/2351).

Anyway,  the next 1.0.0 beta (`1.0.0-beta.5`) will bring a few utils that will help make this easier to deal with. It's not published yet, but you can read about the reasoning and what utils will come in the [updated-but-not-published enum docs here](https://github.com/zth/rescript-relay/blob/master/rescript-relay-documentation/docs/enums.md).

**Comment by zth** [comment]
Closing this as `1.0.0-beta.5` is out now with better enum utils, and the new docs are published as well. Feel free to reopen or open a new issue if there's still questions around how this works.

**Comment by mattdamon108** [comment]
I got your point exactly. It does make sense that the client application can handle the future added value of enum type as the server evolves and enum might be changed later.

But I still think it is a bit harmful to specify two different nominal types for one enum type. I'm still trying to find the related spec in the GraphQL doc and Relay doc, but no gains. I don't know why Relay generates the type with `%future added value` for the enum type as it says.([1](https://github.com/facebook/relay/issues/2351) [2](https://github.com/relay-tools/relay-compiler-language-typescript/issues/81))

I think I'm too much focusing to sound type system. Not sure which is correct.

Anyway, the `decode`, `toString` functions will be much helpful in the real use cases. Thanks!
