### ISSUE TITLE
Query.node type generation

### ISSUE THREAD

**Issue by mattdamon108** [zth/rescript-relay#311]
I found the interesting expression regarding fragment and type generation in your awesome works.

Here is the part of SDL.
```graphql
type Notice implements Node {
  id: ID!
  title: String!
  content: String!
  createdAt: DateTime!
}
```
Query1
```rescript
module Query = %relay(`
  query NoticeDetailQuery($id: ID!) {
    node(id: $id) {
      __typename
      id
      ... on Notice {
        title
        content
        createdAt
      }
    }
  }
`)
```
Query2
```rescript
module Fragment = %relay(`
  fragment NoticeDetail on Notice {
    title
    content
    createdAt
  }
`)

module Query = %relay(`
  query NoticeDetailQuery($id: ID!) {
    node(id: $id) {
      __typename
      id
      ...NoticeDetail
    }
  }
`)
```

`Query1` generates each field of Notice are optional against `type Notice` in SDL. But `Query2` generates each field of Notice without option as per SDL. If I say `... on Notice` is the inline fragment, the inline fragment expression seems to merge fields each by each as `option<t>` with node.id, however, the nominal fragment consists of the type as SDL.

In this case, I'm wondering whether it is how the relay works actually and where I can find this from the relay documentation. Can I have your advice on this?

**Comment by zth** [comment]
@mattdamon108 Hey! If I understand you correctly - yes, this is how Relay type generation works, although I don't believe it's documented anywhere (and they are looking to improve it at some point).

However, RescriptRelay has one special handling (that Relay does not have) that I'm not sure if I've documented anywhere - for the node interface specifically, we automatically "fold" the union into a single option if there's only one union member selection. This is to encourage the use of leveraging the node interface to request single entities, since the node interface is tightly integrated with caching etc.

I'm not sure if that explanation makes sense. There's a test you can look at that demonstrates the behavior: 
https://github.com/zth/rescript-relay/blob/master/packages/rescript-relay/__tests__/Test_nodeInterface.res#L1-L21 

Notice how even though there's a union selection, the query collapses it to a single option where you don't have to explicitly match on the union member `User`.

**Comment by mattdamon108** [comment]
@zth Thank you for explanation. I found the documentation from outside of the relay here. https://graphql.org/learn/queries/#inline-fragments It says,

> To ask for a field on the concrete type, you need to use an inline fragment with a type condition. Because the first fragment is labeled as ... on Droid, the primaryFunction field will only be executed if the Character returned from hero is of the Droid type. Similarly for the height field for the Human type.
Named fragments can also be used in the same way, since a named fragment always has a type attached.

As far as I understand,
* Inline fragment -> Each field is executed by each. It seems each field is merged as part of node.
* Named fragment -> Each field type is persisted as per its type.

I'm sure your ppx generates the correct types for inline fragment expression! Thanks!

**Comment by zth** [comment]
@mattdamon108 awesome, thanks for posting! Is it ok to close this issue?

**Comment by zth** [comment]
Closing, feel free to reopen if needed.

**Comment by mattdamon108** [comment]
Thanks!
